spring:
  datasource:
    url: jdbc:mysql://localhost:3306/velvet-vista_db?useSSL=false
    username: root
    password: Asdf@1999


  #JPA Settings
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    servlet:
      multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB
